import { createStackNavigator } from '@react-navigation/stack';


export const MainRoutes = {
  // SPLASH_SCREEN: 'SplashScreen',
  HOME_SCREEN:'HomeScreen',
  JOBLOGIN_SCREEN: 'JobLoginScreen',
   OTP_OPTION_SCREEN:'OtpOptionScreen',
  DASHBOARD_SCREEN: 'DashboardScreen',
   EMAILVERIFICATION_SCREEN:'EmailVerificationScreen',
   JOBPHONEVERIFICATION_SCREEN:'jobPhoneVerificationScreen',
   SIGN_UP_SCREEN:'SignUpScreen',
  VERIFICATION_SUCCESS_SCREEN:'VerificationSuccessScreen',
   VERIFY_YOUR_ACCOUNT_SCREEN:'VerifyYourAccountScreen',
   JOB_SEEKER_SCREEN:'JobSeekerScreen',
   FOREGETTPASSWORD_SCREEN:'ForgetPasswordScreen',
   RESETPASSWORD:'ResetPassword',
   RESETPASSWORD_SUCCESS:'ResetPasswordSuccess',
   BASIC_DETAILS:'BasicDetails',
   EDUCATION_DETAILS:'EducationDetails',
   WORKEXPERIENCE_DETAILS:'WorkExperienceDetails',
   CERTIFICATION_DETAILS: 'CertificationDetails',
   SKILLS_AND_PREFERANCES: 'SkillsAndPreferances',
   UPLOAD_DOCUMENTS: 'UploadDocuments',
   YOU_ARE_ALL_SET: 'YouAreAllSet',
   JOB_DASHBOARD_SCREEN:'jobDashboardScreen',
 EDUCATION_DETAILS_SCREEN:'EducationDetailsScreen',
 BASIC_DETAILS_SCREEN:'BasicDetailsScreen',
 WORK_EXPERIENCE_SCREEN:'WorkExperienceScreen',
 JOB_OVERVIEW_SCREEN:'JobOverviewScreen',
 JOBPOST_SUCCESS_SCREEN:'JobPostSuccessScreen',
 VIEWJOBS_SCREEN:'ViewJobsScreen',
 EDITJOB_SCREEN:'EditJobScreen',
 JOBUPDATE_SCREEN:'JobUpdateScreen',
 JOBPOSTEDSUCCESSFULLY_SCREEN:'JobPostedSuccesfullyScreen',
 SHAREJOB_SCREEN:'ShareJobScreen',
 POSTJOB_SCREEN:'PostJobScreen',
 EDITCOMPANYDETAILS_SCREEN:'EditCompanyDetailsScreen',
 UPDATECOMPANYDETAILS_SCREEN:'UpdateCompanydetailsscreen',
};

export const RootStackParamList = {
  // [MainRoutes.SPLASH_SCREEN]:{}| undefined,
   [MainRoutes.HOME_SCREEN]: {}|undefined,
  [MainRoutes.JOBLOGIN_SCREEN]:{}| undefined,
  [MainRoutes.DASHBOARD_SCREEN]: {}|undefined,
   [MainRoutes.EMAILVERIFICATION_SCREEN]: {}|undefined,
    [MainRoutes.JOBPHONEVERIFICATION_SCREEN]: {}|undefined,
    [MainRoutes.SIGN_UP_SCREEN]: {}|undefined,
     [MainRoutes.VERIFICATION_SUCCESS_SCREEN]: {}|undefined,
    [MainRoutes.FOREGETTPASSWORD_SCREEN]: {}|undefined,
    [MainRoutes.RESETPASSWORD]: {}|undefined,
    [MainRoutes.RESETPASSWORD_SUCCESS]: {}|undefined,
    [MainRoutes.BASIC_DETAILS]: {}|undefined,
    [MainRoutes.EDUCATION_DETAILS]: {}|undefined,
    [MainRoutes.WORKEXPERIENCE_DETAILS]: {}|undefined,
    [MainRoutes.CERTIFICATION_DETAILS]: {}|undefined,
    [MainRoutes.SKILLS_AND_PREFERANCES]: {}|undefined,
    [MainRoutes.UPLOAD_DOCUMENTS]: {}|undefined,
    [MainRoutes.YOU_ARE_ALL_SET]: {}|undefined,
     [MainRoutes.JOB_DASHBOARD_SCREEN]: {}|undefined,
    [MainRoutes.EDUCATION_DETAILS_SCREEN]: {}|undefined,
    [MainRoutes.BASIC_DETAILS_SCREEN]: {}|undefined,
      [MainRoutes.WORK_EXPERIENCE_SCREEN]: {}|undefined,
      [MainRoutes.JOB_OVERVIEW_SCREEN]: {}|undefined,
      [MainRoutes.JOBPOST_SUCCESS_SCREEN]: {}|undefined,
      [MainRoutes.VIEWJOBS_SCREEN]:{}|undefined,
      [MainRoutes.EDITJOB_SCREEN]:{}|undefined,
      [MainRoutes.JOBUPDATE_SCREEN]:{}|undefined,
      [MainRoutes.JOBPOSTEDSUCCESSFULLY_SCREEN]:{}|undefined,
      [MainRoutes.SHAREJOB_SCREEN]:{}|undefined,
      [MainRoutes.POSTJOB_SCREEN]:{}|undefined,
      [MainRoutes.EDITCOMPANYDETAILS_SCREEN]:{}|undefined,
      [MainRoutes.UPDATECOMPANYDETAILS_SCREEN]:{}|undefined,
};

export const MainStack = createStackNavigator();
export const useNavType = {
  navigate: () => {}, 
};
